locale: "en-US"
title: "Saera Oh"
title_separator: "-"
name: "Saera Oh"
description: "Academic homepage for Saera Oh, Ph.D. Candidate in Agricultural, Food, and Resource Economics and Economics at Michigan State University."
url: "https://sroh722.github.io"
baseurl: ""
repository: "sroh722/sroh722.github.io"
timezone: America/Detroit
permalink: pretty

author:
  name: "Saera Oh"
  avatar: "profile/saera-oh-headshot.jpg"
  bio: "Ph.D. Candidate, Michigan State University"
  location: "East Lansing, Michigan"
  email: "ohsaera@msu.edu"
  googlescholar: "https://scholar.google.com/citations?user=GA4c3iwAAAAJ&hl=en"
  linkedin: "saera-oh-a42281284"
  twitter: "Saera_Oh"

twitter:
  username: "Saera_Oh"

social:
  type: Person
  name: "Saera Oh"
  links:
    - "https://scholar.google.com/citations?user=GA4c3iwAAAAJ&hl=en"
    - "https://www.linkedin.com/in/saera-oh-a42281284"
    - "https://twitter.com/Saera_Oh"

analytics:
  provider: false

comments:
  provider: false

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

include:
  - _pages
  - files
  - images

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README
  - node_modules
  - package.json
  - vendor

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

compress_html:
  clippings: all
  ignore:
    envs: development
